### PR TITLE
Redesigned results page with improved EPA info

### LINKED ISSUE #4: Re-write EPA standards notes to be less alarming.
**Is your feature request related to a problem? Please describe.**
The current EPA standards notes are pretty alarming. They highlight the negative effects of having mineral levels well over the allowed standards and make the minerals seem dangerous.

**Describe the solution you'd like**
Re-write the notes so that they still say the negative effects but also indicate that those are only caused by having levels way over the norm.

### LINKED ISSUE #36: Add EPA standards to results page
The user should be able to click on the red flag/ value to learn about what it means (via EPA standards) on the results page.

### PR DESCRIPTION
**Pull request by reidst**
Updated the results page to be more visually consistent with the instructions page. Result listings with red text indicate that the EPA standards were not met; more information about each chemical can be found by tapping on any result tile.

Note that this PR branch is based on the https://github.com/tedbjurlin/WaterQualityTester/tree/computer_vision branch, which has not yet been merged (see PR #38).

Closes #36 and closes #4

### CODE REVIEW

**Comment by reidst** [comment]
Now that the changes from #42 have been included, this PR is ready for merging. Ted requested that #38 be merged last.

**Comment by Larsonog** [comment]
I am getting an error in the image_color_grid line 15 

Error: Too few positional arguments: 4 required, 1 given.
    ColorStripDetector.detectColors(image.path).then(

**Comment by reidst** [comment]
I must be using an outdated version of the https://github.com/tedbjurlin/water_test_scanner library. I'll fix that in a moment.

**Comment by reidst** [comment]
Ted just let me know that the latest version of the water_test_scanner library is not ready for use. I built this PR on a previous version - specifically the commit `f87655 squash commit tree to remove opencv2.framework` - where it does work. Ted recommends sticking with that version until he can finish the camera updates.

**Pull request merged**
